version: '3.7'

services:
    php-nginx:
        build: php7.4-fpm
        ports:
            - 80:80
        volumes:
            - ./www:/var/www/html

    mariadb:
        image: mariadb:10.6.8
        volumes:
            - vol-mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "dev"
            MYSQL_PASSWORD: "secret"
            MYSQL_DATABASE: "dev"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 8080:80

volumes:
    vol-mariadb:
